### ISSUE TITLE
Out of order

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/redux-delete-codealong#10]
The past several code-alongs have been repeated material already learned / independently coded in actual labs (in this case `Cooking with Redux`.)

**Comment by ValerieHMoore** [comment]
Fyi Micah, other students have suggested moving Cooking with Redux to after the codealongs where the concepts are taught. Seems like a good idea to me :)

**Comment by maxwellbenton** [comment]
Hi @micahshute and @ValerieHMoore,

Thanks for reporting this. We are aware of this issue and are now tracking this and other ordering issues [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3). 

We are currently updating and restructuring the materials in this section and will add this to our internal work queue.  We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of this curriculum.

I'm closing this issue but I invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
