### ISSUE TITLE
Doesn't use UUID

### ISSUE THREAD

**Issue by gac2117** [learn-co-curriculum/redux-delete-codealong#13]
In previous READMEs and labs, we were taught to use `UUID` to generate unique IDs. But why is this codealong using `Math.random()*10000000000000000`? Kind of seems backwards to me...

**Comment by maxwellbenton** [comment]
Hi @gac2117,

Agreed. We've changed this lesson to utilize `uuid` and updated the readme accordingly. Thank you for spotting this and contributing!
