### ISSUE TITLE
code along doesn't contain package.json

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/redux-delete-codealong#2]
This code along doesn't have a package.json file and thus cannot be run via npm an tested.

**Comment by bhollan** [comment]
The `v-000` fork of this lab has a `package.json` in a `redux-delete` folder:
https://github.com/learn-co-students/redux-delete-codealong-v-000

You also might fork/clone this copy of this lab.

CC: @aturkewi

**Comment by Lukeghenco** [comment]
Thanks @walwoodr for some reason the last deployment did not sync up correctly. I just updated the deployment and everything should be working correctly now. Thanks for raising an issue.
