### ISSUE TITLE
Structure of lab is off

### ISSUE THREAD

**Issue by jilustrisimo** [learn-co-curriculum/redux-delete-codealong#3]
@aturkewi @PeterBell @Lukeghenco Unlike most repos this lab requires users to `cd` into the redux-delete dir to be able to run the proper `npm` commands.  Then you have to `cd` back up to the parent directory to push up the code and create a proper PR that learn will recognize. 

People can simply follow along in the code but then they don't see anything in the browser or console.  It should be changed as it may confuse people.

**Comment by Lukeghenco** [comment]
Thanks @jilustrisimo for some reason the last deployment did not sync up correctly. I just updated the deployment and everything should be working correctly now. Thanks for raising an issue.
