### ISSUE TITLE
'this' in handleOnClick() not working

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/redux-delete-codealong#4]
When I code handleOnClick() as ` handleOnClick() {` (as shown in the ReadMe example), instead of `handleOnClick = () => {`, _this_ comes in as null instead of as a valid object reference.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and examples in this lesson and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
