### ISSUE TITLE
manageTodo.js AND Todo.js aren't aligned with reading instructions

### ISSUE THREAD

**Issue by mekowalski** [learn-co-curriculum/redux-delete-codealong#5]
First in the section of the reading titled `GIVE EACH TODO AN ID` the instructions tell the reader to update the `manageTodo.js` file with the provided code.  When this repository is forked and cloned, that file is exactly the same as the provided code.  I don't know what there is to update.

In the following section titled `PASS THIS ID AS A PROPERTY TO EACH TODO COMPONENT` the part on updating the `Todo.js` file provides code to update the `handleOnClick` function with:
>handleOnClick() {
>  this.props.store.dispatch({
>    type: 'DELETE_TODO',
>    id: this.props.id,
>  });
>}

This is confusing and I deem to be incorrect.  I have written this block of code as the reading provides but in the Chrome console, when I click the delete button, I receive an Uncaught TypeError with `'props'` undefined.  Therefore to get this working I use my previous code of:
>handleOnClick = () => {
>    this.props.store.dispatch({
>      type: 'DELETE_TODO',
>      id: this.props.id,
>    });
>}

Lastly, when I do click the delete button the `todos` are supposed to be gone, mine are still present in the browser.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials including the starting code and examples and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
