### ISSUE TITLE
console.log() missing from reducer on master

### ISSUE THREAD

**Issue by kreopelle** [learn-co-curriculum/redux-delete-codealong#8]
Hello! 

While I was working on the redux-delete-codealong, I noticed that the console.log() the Readme references in the reducer is not present in master when the project is cloned down.

This pull request suggests adding the console.log to the initial `src/reducers/manageTodo.js` file.

https://github.com/learn-co-curriculum/redux-delete-codealong/pull/7

Additional feedback regarding this suggestion would be greatly appreciated! 

Best wishes,
Kayla

**Comment by maxwellbenton** [comment]
Hi @kreopelle,

Thanks for the PR! This should now be fixed.
